language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
before_script:
- composer self-update
- composer install --no-interaction
script: 
- vendor/bin/phpunit -c build/phpunitconfig.xml