language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
cache:
    directories:
        - $HOME/.composer/cache
  
before_install:
- composer self-update
install:
- travis_retry composer install --no-interaction --prefer-source
script: 
- vendor/bin/phpunit --configuration ./build/phpunitconfig.xml